source 'https://rubygems.org'

# fixing the ruby version
ruby '2.5.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.2.3'
gem 'rake'
gem 'httparty', '~> 0.16.3'
# action mailer for sending the emails
gem 'actionmailer'
# activeadmin
gem 'activeadmin'
#Flattened ActiceAdmin Theme
gem 'arctic_admin'
gem "bourbon"
# devise for authentication
gem 'devise'
# Use pg as the database for Active Record
gem 'pg', '~> 0.21.0'
# for json response https://github.com/rails-api/active_model_serializers
gem 'active_model_serializers', '~> 0.9.7'
# Use ActiveModel has_secure_password
gem 'bcrypt'
gem 'paperclip', '~> 6.1'
gem 'rdoc', '~> 6.1', '>= 6.1.1'

gem 'redis', '~> 4.1.0'

gem "omniauth-google-oauth2", "~> 0.2.1"
gem 'simplecov'
gem 'simplecov-rcov'

gem 'aasm', '~> 5.0.5'
gem 'pundit'
gem 'kaminari', '~> 1.1.1'
# gem 'paper_trail', '~> 10.3.0'
#For searchable in select field
gem 'activeadmin-searchable_select'
gem "audited", "~> 4.7"
gem 'sidekiq'
gem 'sidekiq-status', '~> 1.1.3'
gem 'exception_notification', '~> 4.3.0'
gem 'puma'
# Use SCSS for stylesheets
gem 'sass-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'fancybox2-rails'
gem 'binding_of_caller'
gem 'remotipart'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# Use Inline Editing 
gem 'best_in_place', '~> 3.0.1'

# Use thin as the app server
gem 'nokogiri'
gem 'oauth'
gem 'omniauth'
gem 'omniauth-linkedin'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'google-api-client', '~> 0.11'
gem 'googleauth'
gem 'google_drive'
gem 'google-spreadsheet-ruby', '~> 0.3.1'
gem 'whenever', require: false
gem 'caxlsx'
gem 'caxlsx_rails'

group :development, :test do
	gem 'byebug'
	gem 'bullet'
# rspec for testing
	gem 'rspec'
	gem "rspec-rails"
	gem "factory_girl_rails", '~>4.2.1'
	gem 'faker'
 	gem 'better_errors'
end

group :doc do
	# bundle exec rake doc:rails generates the API under doc/api.
	gem 'sdoc', :require => false
end

group :deployment do
# Use Capistrano for deployment
	gem 'capistrano', '~> 3.0.1'
# rails specific capistrano functions
	gem 'capistrano-rails', '~> 1.1.0'
end

group :test do
	gem 'capybara'
	gem 'chromedriver-helper', '~> 0.0.5'
	gem 'cucumber'
	# database_cleaner is not required, but highly recommended
	gem 'database_cleaner'
	gem 'headless'
	gem 'selenium-webdriver'
	gem "launchy", "~> 2.4.2"
	gem 'shoulda-matchers', require: false
end
